image: Ubuntu

install:
- pip install --requirement requirements.txt
- docker run --rm --detach -p 4445:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome

test_script:
- python test.py

build: off
