image: Ubuntu
build: off
stack: python 3.9
init:
- image=selenium/standalone-chrome:beta
- image=selenium/standalone-chrome
install:
- pip install --quiet --progress-bar=off --requirement requirements.txt
- docker pull $image
# - docker run --rm --detach -p 4445:4444 -v /dev/shm:/dev/shm $image
# - docker run --rm -p 4445:4444 -p 7900:7900 --shm-size 2g $image &
# - docker run --rm -p 4445:4444 -p 7900:7900 --shm-size 2g $imate &
- docker run --rm --detach -p 4445:4444 -p 7900:7900 --shm-size 4g $imate
test_script:
- sleep 1m
- python test.py
